version: '3.8'

services:
  aqi-api:
    build: ./api
    container_name: aqi-api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aqi-network

  aqi-web:
    build: ./web
    container_name: aqi-web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://aqi-api:8000
    depends_on:
      - aqi-api
    networks:
      - aqi-network

networks:
  aqi-network:
    driver: bridge